"""Reporter — DiffResult → JSON / Markdown."""
from __future__ import annotations

import json

from .checker import (
    DiffResult,
    Verdict,
)

_VERDICT_EMOJI = {
    Verdict.NO_CHANGE: "✅",
    Verdict.COMPATIBLE: "✅",
    Verdict.SOURCE_BREAK: "⚠️",
    Verdict.BREAKING: "❌",
}

_VERDICT_LABEL = {
    Verdict.NO_CHANGE: "NO_CHANGE",
    Verdict.COMPATIBLE: "COMPATIBLE",
    Verdict.SOURCE_BREAK: "SOURCE_BREAK",
    Verdict.BREAKING: "BREAKING",
}


def to_json(result: DiffResult, indent: int = 2) -> str:
    d = {
        "library": result.library,
        "old_version": result.old_version,
        "new_version": result.new_version,
        "verdict": result.verdict.value,
        "summary": {
            "breaking": len(result.breaking),
            "source_breaks": len(result.source_breaks),
            "compatible_additions": len(result.compatible),
            "total_changes": len(result.changes),
        },
        "changes": [
            {
                "kind": c.kind.value,
                "symbol": c.symbol,
                "description": c.description,
                "old_value": c.old_value,
                "new_value": c.new_value,
            }
            for c in result.changes
        ],
    }
    return json.dumps(d, indent=indent)


def to_markdown(result: DiffResult) -> str:
    v = result.verdict
    emoji = _VERDICT_EMOJI[v]
    label = _VERDICT_LABEL[v]

    lines: list[str] = [
        f"# ABI Report: {result.library}",
        "",
        "| | |",
        "|---|---|",
        f"| **Old version** | `{result.old_version}` |",
        f"| **New version** | `{result.new_version}` |",
        f"| **Verdict** | {emoji} `{label}` |",
        f"| Breaking changes | {len(result.breaking)} |",
        f"| Source-level breaks | {len(result.source_breaks)} |",
        f"| Compatible additions | {len(result.compatible)} |",
        "",
    ]

    if result.breaking:
        lines += ["## ❌ Breaking Changes", ""]
        for c in result.breaking:
            old_new = ""
            if c.old_value and c.new_value:
                old_new = f" (`{c.old_value}` → `{c.new_value}`)"
            elif c.old_value:
                old_new = f" (`{c.old_value}`)"
            lines.append(f"- **{c.kind.value}**: {c.description}{old_new}")
        lines.append("")

    if result.source_breaks:
        lines += ["## ⚠️ Source-Level Breaks", ""]
        for c in result.source_breaks:
            lines.append(f"- **{c.kind.value}**: {c.description}")
        lines.append("")

    if result.compatible:
        lines += ["## ✅ Compatible Additions", ""]
        for c in result.compatible:
            lines.append(f"- {c.description}")
        lines.append("")

    if not result.changes:
        lines.append("_No ABI changes detected._")

    if result.suppressed_count > 0:
        lines.append("")
        lines.append(f"> ℹ️ {result.suppressed_count} change(s) suppressed via suppression file")

    lines += [
        "---",
        "## Legend",
        "",
        "| Verdict | Meaning |",
        "|---------|---------|",
        "| ✅ NO_CHANGE | Identical ABI |",
        "| ✅ COMPATIBLE | Only additions (backward compatible) |",
        "| ⚠️ SOURCE_BREAK | Source-level API change, binary compatible |",
        "| ❌ BREAKING | Binary ABI break — recompilation required |",
        "",
        "_Generated by [abicheck](https://github.com/napetrov/abicheck)_",
    ]
    return "\n".join(lines)
