#!/usr/bin/env python3
"""Generate the docs/examples/ tree from examples/ + ground_truth.json.

Run before `mkdocs build`. Idempotent. Pass --check to fail if regeneration
would change the tree (used by CI as a drift gate).
"""

from __future__ import annotations

import argparse
import filecmp
import json
import re
import shutil
import sys
import tempfile
from collections import defaultdict
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXAMPLES_DIR = ROOT / "examples"
DOCS_EXAMPLES_DIR = ROOT / "docs" / "examples"
GROUND_TRUTH = EXAMPLES_DIR / "ground_truth.json"
REPO_BLOB = "https://github.com/napetrov/abicheck/blob/main"

VERDICT_META = {
    "BREAKING": {
        "icon": "🔴",
        "slug": "breaking",
        "label": "BREAKING",
        "blurb": "ABI breaks: existing consumers will fail at runtime.",
    },
    "API_BREAK": {
        "icon": "🟠",
        "slug": "api-break",
        "label": "API_BREAK",
        "blurb": "Source-level / API-only breaks; recompilation fails or behavior shifts.",
    },
    "COMPATIBLE_WITH_RISK": {
        "icon": "🟡",
        "slug": "compatible-risk",
        "label": "COMPATIBLE_WITH_RISK",
        "blurb": "Backward-compatible at the symbol level but with behavioral risk.",
    },
    "COMPATIBLE": {
        "icon": "🟢",
        "slug": "compatible",
        "label": "COMPATIBLE",
        "blurb": "Backward-compatible changes (additions or quality-only).",
    },
    "NO_CHANGE": {
        "icon": "✅",
        "slug": "no-change",
        "label": "NO_CHANGE",
        "blurb": "Identical ABI/API — baseline control cases.",
    },
}

CATEGORY_META = {
    "breaking": {
        "label": "Breaking",
        "blurb": "Listed in `BREAKING_KINDS` — runtime ABI break.",
    },
    "api_break": {
        "label": "API Break",
        "blurb": "Listed in `API_BREAK_KINDS` — source/API-level break.",
    },
    "risk": {
        "label": "Risk",
        "blurb": "Listed in `RISK_KINDS` — symbol-compatible but behaviorally risky.",
    },
    "addition": {
        "label": "Addition (Compatible)",
        "blurb": "Listed in `ADDITION_KINDS` — backward-compatible additions.",
    },
    "quality": {
        "label": "Quality (Compatible)",
        "blurb": "Listed in `QUALITY_KINDS` — metadata/quality issues, not ABI breaks.",
    },
    "no_change": {
        "label": "No Change",
        "blurb": "Identical ABI/API — sanity-check baselines.",
    },
}

VERDICT_ORDER = [
    "BREAKING",
    "API_BREAK",
    "COMPATIBLE_WITH_RISK",
    "COMPATIBLE",
    "NO_CHANGE",
]
CATEGORY_ORDER = ["breaking", "api_break", "risk", "addition", "quality", "no_change"]

# Normalize platform ids from ground_truth.json to their canonical user-facing
# spelling. ground_truth.json uses lowercase ids so it can match Python platform
# checks; docs should show the canonical brand name.
PLATFORM_DISPLAY = {
    "linux": "Linux",
    "macos": "macOS",
    "windows": "Windows",
}

WARNING = (
    "<!-- DO NOT EDIT — generated by scripts/gen_examples_docs.py. "
    "Source: examples/<case>/README.md + examples/ground_truth.json. -->\n"
)


@dataclass
class Case:
    name: str
    title: str
    verdict: str
    category: str
    platforms: list[str]
    abi_break: bool
    api_break: bool
    bad_practice: bool
    expected_kinds: list[str]
    body: str  # README content with H1 stripped


def _read_case(name: str, meta: dict) -> Case:
    readme = EXAMPLES_DIR / name / "README.md"
    if not readme.exists():
        raise FileNotFoundError(f"missing per-case README: {readme}")
    text = readme.read_text(encoding="utf-8")
    m = re.match(r"\s*#\s+(.+?)\n", text)
    if not m:
        raise ValueError(f"{readme}: first line must be H1 (# Title)")
    title = m.group(1).strip()
    body = text[m.end() :].lstrip("\n")
    body = _rewrite_links(body)
    return Case(
        name=name,
        title=title,
        verdict=meta["expected"],
        category=meta["category"],
        platforms=list(meta.get("platforms", [])),
        abi_break=bool(meta.get("abi_break", False)),
        api_break=bool(meta.get("api_break", False)),
        bad_practice=bool(meta.get("bad_practice", False)),
        expected_kinds=list(meta.get("expected_kinds", [])),
        body=body,
    )


def _rewrite_links(body: str) -> str:
    # Rewrite repo-relative links like ../abicheck/... → GitHub blob URLs.
    def repl(m: re.Match) -> str:
        text, target = m.group(1), m.group(2)
        if target.startswith(("http://", "https://", "#", "mailto:")):
            return m.group(0)
        # Bare filenames like v1.c, app.cpp → point to the case directory on GitHub.
        if target.startswith("../"):
            url = f"{REPO_BLOB}/{target.lstrip('./')}"
        elif "/" not in target and "." in target:
            url = f"{REPO_BLOB}/examples/__CASE__/{target}"
        else:
            url = target
        return f"[{text}]({url})"

    return re.sub(r"\[([^\]]+)\]\(([^)]+)\)", repl, body)


def _meta_table(case: Case) -> str:
    vinfo = VERDICT_META[case.verdict]
    cinfo = CATEGORY_META[case.category]
    flags = []
    if case.abi_break:
        flags.append("ABI break")
    if case.api_break:
        flags.append("API break")
    if case.bad_practice:
        flags.append("Bad practice")
    flag_str = ", ".join(flags) if flags else "—"
    platforms = (
        ", ".join(PLATFORM_DISPLAY.get(p, p) for p in case.platforms)
        if case.platforms
        else "—"
    )
    kinds = (
        ", ".join(f"`{k}`" for k in case.expected_kinds) if case.expected_kinds else "—"
    )
    return (
        "| Field | Value |\n"
        "|-------|-------|\n"
        f"| **Verdict** | {vinfo['icon']} **{vinfo['label']}** |\n"
        f"| **Category** | {cinfo['label']} |\n"
        f"| **Platforms** | {platforms} |\n"
        f"| **Flags** | {flag_str} |\n"
        f"| **Detected `ChangeKind`s** | {kinds} |\n"
        f"| **Source files** | [browse on GitHub]({REPO_BLOB}/examples/{case.name}/) |\n"
    )


def _source_links(case: Case) -> str:
    case_dir = EXAMPLES_DIR / case.name
    files = sorted(
        p.name for p in case_dir.iterdir() if p.is_file() and p.name != "README.md"
    )
    if not files:
        return ""
    lines = [f"- [`{f}`]({REPO_BLOB}/examples/{case.name}/{f})" for f in files]
    return "## Source files\n\n" + "\n".join(lines) + "\n"


def _render_case_page(case: Case) -> str:
    body = case.body.replace("__CASE__", case.name)
    parts = [
        WARNING,
        f"# {case.title}\n\n",
        _meta_table(case),
        "\n",
        body.rstrip() + "\n\n",
        "---\n\n",
        _source_links(case),
        "\n",
        f"_See also: [Examples overview](index.md) · "
        f"[All {VERDICT_META[case.verdict]['label']} cases](by-verdict/{VERDICT_META[case.verdict]['slug']}.md) · "
        f"[Category: {CATEGORY_META[case.category]['label']}](by-category/{case.category}.md)._\n",
    ]
    return "".join(parts)


def _verdict_counts(cases: list[Case]) -> dict[str, int]:
    out: dict[str, int] = defaultdict(int)
    for c in cases:
        out[c.verdict] += 1
    return out


def _case_row(case: Case) -> str:
    vinfo = VERDICT_META[case.verdict]
    return (
        f"| [{case.name}]({case.name}.md) "
        f"| {case.title.split(':', 1)[-1].strip()} "
        f"| {vinfo['icon']} {vinfo['label']} "
        f"| {CATEGORY_META[case.category]['label']} |"
    )


def _render_index(cases: list[Case]) -> str:
    counts = _verdict_counts(cases)
    lines = [
        WARNING,
        "# Examples & Case Encyclopedia\n\n",
        f"This catalog covers **{len(cases)} cases** demonstrating real-world "
        "ABI/API change scenarios for C/C++ shared libraries. Each case is a "
        "minimal compilable v1/v2 pair plus a consumer (`app.c`/`app.cpp`) "
        "that demonstrates the actual runtime effect.\n\n",
        "Use this catalog to:\n\n",
        "- Learn **what kinds of changes break ABI** vs. which are safe.\n"
        "- See the **runtime failure mode** for each break (crash, wrong output, silent corruption…).\n"
        "- Look up the **mitigation pattern** for a specific change.\n"
        "- Cross-reference detected [`ChangeKind`s](../reference/change-kinds.md) with concrete reproductions.\n\n",
        "> **Ground truth.** Expected verdicts and detected change kinds live in "
        f"[`examples/ground_truth.json`]({REPO_BLOB}/examples/ground_truth.json) and are the "
        "single source of truth — these pages are generated from that file plus per-case "
        f"`README.md` files under [`examples/`]({REPO_BLOB}/examples/).\n\n",
        "## Verdict distribution\n\n",
        "| Verdict | Count | What it means |\n",
        "|---------|-------|---------------|\n",
    ]
    for v in VERDICT_ORDER:
        info = VERDICT_META[v]
        lines.append(
            f"| {info['icon']} [{info['label']}](by-verdict/{info['slug']}.md) "
            f"| {counts.get(v, 0)} | {info['blurb']} |\n"
        )
    lines.append("\n## How to read a case page\n\n")
    lines.append(
        "Each case page starts with a metadata table (verdict, category, "
        "platforms, detected change kinds) followed by:\n\n"
        "- **What changes / what breaks** — the source diff between v1 and v2.\n"
        "- **Why abicheck (or abidiff/ABICC) catches it** — detection mechanism.\n"
        "- **Real Failure Demo** — exact shell commands that reproduce the runtime effect.\n"
        "- **How to fix** — the mitigation pattern, where the README documents one.\n"
        "- **Real-world example** — historical occurrences in widely-used libraries.\n"
        "- **References** — links to relevant standards, manuals, and abicheck source.\n\n"
        "Source files (`v1.*`, `v2.*`, `app.*`, `CMakeLists.txt`) are linked at the bottom of every page.\n\n"
    )
    lines.append("## Browse by category\n\n")
    by_cat: dict[str, list[Case]] = defaultdict(list)
    for c in cases:
        by_cat[c.category].append(c)
    lines.append("| Category | Cases | What it covers |\n")
    lines.append("|----------|-------|----------------|\n")
    for cat in CATEGORY_ORDER:
        info = CATEGORY_META[cat]
        n = len(by_cat.get(cat, []))
        lines.append(
            f"| [{info['label']}](by-category/{cat}.md) | {n} | {info['blurb']} |\n"
        )
    lines.append("\n## All cases\n\n")
    lines.append("| Case | Title | Verdict | Category |\n")
    lines.append("|------|-------|---------|----------|\n")
    for c in sorted(cases, key=lambda c: c.name):
        lines.append(_case_row(c) + "\n")
    return "".join(lines)


def _render_group_index(
    title: str,
    blurb: str,
    cases: list[Case],
    *,
    backlink: str = "../index.md",
) -> str:
    lines = [
        WARNING,
        f"# {title}\n\n",
        blurb + "\n\n",
        f"_{len(cases)} case(s)._ [← back to all examples]({backlink})\n\n",
    ]
    if not cases:
        lines.append("_No cases in this group._\n")
        return "".join(lines)
    lines.append("| Case | Title | Verdict | Category |\n")
    lines.append("|------|-------|---------|----------|\n")
    for c in sorted(cases, key=lambda c: c.name):
        vinfo = VERDICT_META[c.verdict]
        lines.append(
            f"| [{c.name}](../{c.name}.md) "
            f"| {c.title.split(':', 1)[-1].strip()} "
            f"| {vinfo['icon']} {vinfo['label']} "
            f"| {CATEGORY_META[c.category]['label']} |\n"
        )
    return "".join(lines)


def _load_cases() -> list[Case]:
    data = json.loads(GROUND_TRUTH.read_text(encoding="utf-8"))
    cases = []
    for name, meta in data["verdicts"].items():
        if meta["expected"] not in VERDICT_META:
            raise ValueError(f"{name}: unknown verdict {meta['expected']!r}")
        if meta["category"] not in CATEGORY_META:
            raise ValueError(f"{name}: unknown category {meta['category']!r}")
        cases.append(_read_case(name, meta))
    return cases


def _write(path: Path, content: str) -> None:
    # Write in binary with LF newlines so the on-disk tree is byte-stable across
    # platforms — required for the --check drift gate to work on Windows.
    path.write_bytes(content.encode("utf-8"))


def _normalize(data: bytes) -> bytes:
    # Strip BOM and normalize CRLF/CR → LF so the comparator survives a Windows
    # checkout where core.autocrlf might have rewritten committed files.
    if data.startswith(b"\xef\xbb\xbf"):
        data = data[3:]
    return data.replace(b"\r\n", b"\n").replace(b"\r", b"\n")


def _files_match(a: Path, b: Path) -> bool:
    return _normalize(a.read_bytes()) == _normalize(b.read_bytes())


def _write_tree(out_dir: Path, cases: list[Case]) -> None:
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)
    (out_dir / "by-verdict").mkdir()
    (out_dir / "by-category").mkdir()

    _write(out_dir / "index.md", _render_index(cases))

    by_verdict: dict[str, list[Case]] = defaultdict(list)
    by_category: dict[str, list[Case]] = defaultdict(list)
    for c in cases:
        by_verdict[c.verdict].append(c)
        by_category[c.category].append(c)

    for v in VERDICT_ORDER:
        info = VERDICT_META[v]
        _write(
            out_dir / "by-verdict" / f"{info['slug']}.md",
            _render_group_index(
                title=f"{info['icon']} {info['label']} cases",
                blurb=info["blurb"],
                cases=by_verdict.get(v, []),
            ),
        )

    for cat in CATEGORY_ORDER:
        info = CATEGORY_META[cat]
        _write(
            out_dir / "by-category" / f"{cat}.md",
            _render_group_index(
                title=f"{info['label']} cases",
                blurb=info["blurb"],
                cases=by_category.get(cat, []),
            ),
        )

    for c in cases:
        _write(out_dir / f"{c.name}.md", _render_case_page(c))


def _trees_match(a: Path, b: Path) -> bool:
    cmp = filecmp.dircmp(a, b)
    if cmp.left_only or cmp.right_only or cmp.funny_files:
        return False
    for f in cmp.common_files:
        if not _files_match(a / f, b / f):
            return False
    for sub in cmp.common_dirs:
        if not _trees_match(a / sub, b / sub):
            return False
    return True


def _print_diff(expected: Path, actual: Path) -> None:
    cmp = filecmp.dircmp(expected, actual)
    if cmp.left_only:
        print(f"  missing in {actual}: {cmp.left_only}", file=sys.stderr)
    if cmp.right_only:
        print(f"  stale in {actual}: {cmp.right_only}", file=sys.stderr)
    diffs = [f for f in cmp.common_files if not _files_match(expected / f, actual / f)]
    if diffs:
        print(f"  changed: {diffs}", file=sys.stderr)
    for sub in cmp.common_dirs:
        _print_diff(expected / sub, actual / sub)


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail (exit 1) if the on-disk tree differs from what would be generated.",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)

    cases = _load_cases()

    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_out = Path(tmp) / "examples"
            _write_tree(tmp_out, cases)
            if not DOCS_EXAMPLES_DIR.exists() or not _trees_match(
                tmp_out, DOCS_EXAMPLES_DIR
            ):
                print(
                    "docs/examples/ is out of date. Run: python scripts/gen_examples_docs.py",
                    file=sys.stderr,
                )
                if DOCS_EXAMPLES_DIR.exists():
                    _print_diff(tmp_out, DOCS_EXAMPLES_DIR)
                return 1
        print(f"docs/examples/ is up to date ({len(cases)} cases).")
        return 0

    _write_tree(DOCS_EXAMPLES_DIR, cases)
    print(
        f"Generated {len(cases)} case pages in {DOCS_EXAMPLES_DIR.relative_to(ROOT)}/."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
