#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2024 CodeRabbit Inc.
"""gen_detector_spec.py — the formal detector specification matrix.

Fuses the per-``ChangeKind`` facts that currently live scattered across the
codebase into one visible, machine-readable specification (the recommendation's
"formal detectability specification"):

* **category** — which partition the kind belongs to (breaking / api_break /
  risk / addition / quality), from ``checker_policy`` (BREAKING_KINDS …).
* **default_verdict** + **severity** + **doc_slug** — from ``policy_for(kind)``.
* **min_evidence** — the weakest evidence layer (L0 symbols … L4 source) at
  which the kind first becomes detectable, from ``scripts/evidence_tiers``.

Outputs Markdown (``docs/reference/detector-spec.md``) and JSON
(``docs/reference/detector-spec.json``). ``--check`` regenerates in memory and
fails if either file is stale (CI gate), mirroring ``gen_examples_docs.py``.

Usage:
    python scripts/gen_detector_spec.py            # write the files
    python scripts/gen_detector_spec.py --check     # verify in sync (CI)
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent
MD_PATH = REPO_DIR / "docs" / "reference" / "detector-spec.md"
JSON_PATH = REPO_DIR / "docs" / "reference" / "detector-spec.json"

GENERATED_NOTE = (
    "<!-- GENERATED by scripts/gen_detector_spec.py — do not edit by hand. "
    "Run `python scripts/gen_detector_spec.py` to regenerate. -->"
)


def _category_of(kind, policy) -> str:
    """Return the partition name for *kind*."""
    if kind in policy.BREAKING_KINDS:
        return "breaking"
    if kind in policy.API_BREAK_KINDS:
        return "api_break"
    if kind in policy.RISK_KINDS:
        return "risk"
    if kind in policy.ADDITION_KINDS:
        return "addition"
    if kind in policy.QUALITY_KINDS:
        return "quality"
    return "unknown"


def build_spec() -> list[dict[str, str]]:
    """Build the per-ChangeKind spec rows (sorted by kind value)."""
    sys.path.insert(0, str(REPO_DIR / "scripts"))
    from evidence_tiers import EVIDENCE_TIER_BY_KIND  # type: ignore[import-not-found]

    from abicheck import checker_policy as policy
    from abicheck.checker_policy import ChangeKind, policy_for

    rows: list[dict[str, str]] = []
    for kind in sorted(ChangeKind, key=lambda k: k.value):
        entry = policy_for(kind)
        rows.append({
            "kind": kind.value,
            "category": _category_of(kind, policy),
            "default_verdict": entry.default_verdict.value,
            "severity": entry.severity,
            "min_evidence": EVIDENCE_TIER_BY_KIND.get(kind.value, "?"),
            "doc_slug": entry.doc_slug,
        })
    return rows


def render_markdown(rows: list[dict[str, str]]) -> str:
    lines = [
        GENERATED_NOTE,
        "",
        "# Detector specification matrix",
        "",
        f"One row per `ChangeKind` ({len(rows)} total). Columns fuse the verdict "
        "partition (`checker_policy`), default policy (`policy_for`), and the "
        "weakest evidence layer at which the kind becomes detectable "
        "(`scripts/evidence_tiers`).",
        "",
        "| ChangeKind | Category | Default verdict | Severity | Min evidence | Doc slug |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| `{r['kind']}` | {r['category']} | `{r['default_verdict']}` | "
            f"`{r['severity']}` | {r['min_evidence']} | `{r['doc_slug']}` |"
        )
    lines.append("")
    return "\n".join(lines)


def render_json(rows: list[dict[str, str]]) -> str:
    return json.dumps(
        {"description": "Formal detector specification matrix (generated).",
         "count": len(rows), "detectors": rows},
        indent=2,
    ) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="Verify the generated files are in sync; do not write.")
    args = ap.parse_args(argv)

    rows = build_spec()
    md = render_markdown(rows)
    js = render_json(rows)

    if args.check:
        stale = []
        for path, want in ((MD_PATH, md), (JSON_PATH, js)):
            got = path.read_text(encoding="utf-8") if path.exists() else None
            if got != want:
                stale.append(path.relative_to(REPO_DIR))
        if stale:
            print("ERROR: detector spec out of date:", file=sys.stderr)
            for p in stale:
                print(f"  - {p}", file=sys.stderr)
            print("Run: python scripts/gen_detector_spec.py", file=sys.stderr)
            return 1
        print(f"detector spec in sync ({len(rows)} kinds)")
        return 0

    MD_PATH.parent.mkdir(parents=True, exist_ok=True)
    MD_PATH.write_text(md, encoding="utf-8")
    JSON_PATH.write_text(js, encoding="utf-8")
    print(f"wrote {MD_PATH.relative_to(REPO_DIR)} and "
          f"{JSON_PATH.relative_to(REPO_DIR)} ({len(rows)} kinds)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
